import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0/client';
import { useEffect, useRef, useState } from 'react';
import AnchorLink from '../components/AnchorLink'
import { CONSTANTS } from './assets/Constants';
import Loading from '../components/Loading';
import { SpotifyAuth } from './helpers/SpotifyAuth';
import Dashboard from '../components/Dashboard';

export default function Home() {
  const { user, isLoading } = useUser();
  const [ spotifyAuthenticated, setSpotifyAuthenticated ] = useState(false);
  const spotifyAuth = useRef<SpotifyAuth>();
  const spotifyAuthURL = CONSTANTS.SPOTIFY_AUTH_URL;

  // Handles spotify authentication
  async function handleSpotifyAuth() {
    if (!spotifyAuthenticated) {
      const params = new URLSearchParams(window.location.search);
      const code = params.get('code');
      if (code) {
        spotifyAuth.current = new SpotifyAuth(code);
        setSpotifyAuthenticated(true);
        return;
      } 
    }
  }
  useEffect(() => {
    if (user) handleSpotifyAuth();
  }), [];

  if (isLoading) {
    return (
      <div>
        <Loading />
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Partyfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { 
        !user && <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Partyfy!</h1>
          <p className={styles.description}>A controllable Spotify Party without the hassle of sharing a playlist.</p>
          <AnchorLink
            href="/api/auth/login"
            className="btn btn-primary btn-margin"
            tabIndex={0}
            testId="navbar-login-desktop" icon={null}>
            Log in
          </AnchorLink>
        </main> 
      }
      {
        user && <main className={`${styles.main_loggedin} `}>
          <nav className='d-flex flex-row justify-content-between'>
            <h2 className={`${styles.title} m-4`}>{`Welcome back, ${user.given_name}!`}</h2>
            <AnchorLink
              href="/api/auth/logout"
              className="btn btn-primary btn-margin m-4"
              icon={null}
              testId="navbar-logout-mobile"
              tabIndex={0}>
              Log out
            </AnchorLink>
          </nav>
          { 
            spotifyAuthenticated
            ? 
            <div className="d-flex flex-column justify-content-center align-items-center">
              <Dashboard spotifyAuth={spotifyAuth.current} setSpotifyAuthenticated={setSpotifyAuthenticated} /> 
            </div>
            :
            <div className={`${styles.spotifylogin} d-flex flex-column justify-content-center align-items-center`}>
              <h3 className="m-4">You're almost ready to party!</h3>
              <p className="m-4">To get started, you'll need to authenticate your Spotify account.</p>
                <AnchorLink
                  href={spotifyAuthURL}
                  className="btn btn-success btn-margin m-4 decoration-none"
                  icon={null}
                  testId="navbar-logout-mobile"
                  tabIndex={0}>
                  Authenticate Spotify
                </AnchorLink>
            </div>
          }

        </main>
      }
    </>
  )
}
